In [3]:
import torch
import numpy as np
import tensorflow as tf

In [5]:
t1 = torch.tensor([1, 2, 3, 4])
print("1D Tensor:", t1)

1D Tensor: tensor([1, 2, 3, 4])


In [7]:
t2 = torch.rand((3, 3))
print("\nRandom 3x3 Tensor:\n", t2)


Random 3x3 Tensor:
 tensor([[0.2961, 0.3649, 0.8707],
        [0.4975, 0.0202, 0.4012],
        [0.4706, 0.3331, 0.7744]])


In [9]:
t3 = torch.zeros((2, 5))
print("\n2x5 Zeros Tensor:\n", t3)


2x5 Zeros Tensor:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [11]:
A = torch.tensor([1, 2, 3], dtype=torch.float32)
B = torch.tensor([4, 5, 6], dtype=torch.float32)

# Addition
add_result = A + B
print("\nAddition:", add_result)

# Subtraction
sub_result = A - B
print("Subtraction:", sub_result)

# Multiplication (element-wise)
mul_result = A * B
print("Element-wise Multiplication:", mul_result)


Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Element-wise Multiplication: tensor([ 4., 10., 18.])


In [13]:
# Create NumPy array
np_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convert NumPy → PyTorch
torch_tensor = torch.from_numpy(np_array)
print("\nNumPy to PyTorch Tensor:\n", torch_tensor)

# Convert NumPy → TensorFlow
tf_tensor = tf.convert_to_tensor(np_array)
print("\nNumPy to TensorFlow Tensor:\n", tf_tensor)


NumPy to PyTorch Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

NumPy to TensorFlow Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [15]:
import torch

# Create tensor with value 5.0 and enable gradient tracking
x = torch.tensor(5.0, requires_grad=True)
print("PyTorch tensor x:", x)


PyTorch tensor x: tensor(5., requires_grad=True)


In [17]:
# Step 1: Create tensor x with gradient tracking
x = torch.tensor(5.0, requires_grad=True)

# Step 2: Compute y = x^2 + 3x + 2
y = x**2 + 3*x + 2
print("PyTorch y:", y.item())

PyTorch y: 42.0


In [ ]:
x = torch.tensor(5.0, requires_grad=True)

# Define the function y = x^2 + 3x + 2
y = x**2 + 3*x + 2

# Compute gradient dy/dx
y.backward()
print("PyTorch dy/dx:", x.grad.item())